name: 'Backup via git and rsync from remote server'
description: 'Simple backup action of your files from a remote server via rsync over ssh to the GitHub repository'
author: 'setnemo'
  path:
    description: 'The local path'
    required: false
    default: ''
  remote_path:
    description: 'The remote path'
    required: true
  remote_host:
    description: 'The remote host'
    required: true
  remote_port:
    description: 'The remote port'
    required: false
    default: 22
  remote_user:
    description: 'The remote user'
    required: true
  remote_key:
    description: 'The remote key'
    required: true
  remote_key_pass:
    description: 'The remote key passphrase'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'send'  
  color: 'gray-dark'
